### ISSUE TITLE
php如何从注册中心访问java的微服务？如何通过Application获取到java微服务的url？

### ISSUE THREAD

**Issue by hitIer** [tangaiyun/SpringCloudOpenresty#1]
感谢作者给的代码，我是要用php注册到spring cloud eureka，现在我已经能够注册上去了。java能访问我的微服务，但是我该怎么访问java的微服务？如何通过Application获取到java微服务的url？

**Comment by tangaiyun** [comment]
再PHP中，我建议你通过zuul访问java服务，或者你自己通过eureka的REST API得到注册服务的节点信息，然后使用一个负载均衡策略（比如随机，RR）去选择一个服务节点，简单的讲，你要开发一个PHP版本的Ribbon 组件，你可以参考 https://github.com/PavelLoparev/php-eureka-client
